esphome:
  name: $device_name
  friendly_name: $friendly_name

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret ap_password

captive_portal:
web_server:

button:
  - id: factory_reset_button
    platform: factory_reset
    name: Restart with Factory Default Settings
    on_press:
      then:
        - logger.log: "Factory Reset Called"