name: Auto Release

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:    
      - main
    # paths:
    #   - '**/release-notes.md'   

jobs:
  build-and-release:
    permissions:
      contents: write         # write permission is required to create a github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Release Summary
        run: |  # preserve multiline text
          echo "RELEASE_SUMMARY<<EOF" >> $GITHUB_ENV
          cat release-notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: ESPHome Builder
        id: esphome-build
        uses: esphome/build-action@v7
        with:
          yaml-file: screen-time.yaml
          version: "2024.11.2"
          cache: true
          complete-manifest: true  # needed for auto updater
          release-summary: ${{ env.RELEASE_SUMMARY }}
          release-url: https://github.com/alex-tomin/screen-time/releases/latest
      
      - run : echo "The project version is ${{ steps.esphome-build.outputs.project-version }}"

      - name: Release
        uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: true
          body_path: release-notes.md
          tag_name: ${{ steps.esphome-build.outputs.project-version }}
          generate_release_notes: true
          files: |
            screen-time-esp32/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: firmware
          path: screen-time-esp32/*
          # The desired behavior if no files are found using the provided path.               
