name: Auto Release

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:    
      - main
    paths:
      - '**/RELEASE'

jobs:
  build-and-release:
    permissions:
      contents: write         # write permission is required to create a github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ESPHome Builder
        uses: esphome/build-action@v4.0.3
        with:
          yaml-file: screen-time.yaml
          version: "2024.9.2"
          cache: true
          #release-summary: # optional, default is 
          # Release URL
          #release-url: # optional, default is 


      - uses: release-drafter/release-drafter@v6
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: firmware
          path: screen-time-esp32/*
          # The desired behavior if no files are found using the provided path.               
